### ISSUE TITLE
Ability to specify the modal node by Id

### ISSUE THREAD

**Issue by hendrul** [AlexanderRichey/styled-react-modal#19]
I'm ssr some components including the html where the components are rendered, I would like my modals to render over a specific component by Id.

Something like this portal could help

```js
import { memo, useEffect, useRef, useState } from 'react'
import { createPortal } from 'react-dom'

const Portal = ({ id, children }) => {
  const el = useRef(
    document.getElementById(id) || document.createElement('div')
  )
  const [dynamic] = useState(!el.current.parentElement)
  useEffect(() => {
    if (dynamic) {
      el.current.id = id
      document.body.appendChild(el.current)
    }
    return () => {
      if (dynamic && el.current.parentElement) {
        el.current.parentElement.removeChild(el.current)
      }
    }
  }, [id])
  return createPortal(children, el.current)
}

export default memo(Portal)

```

**Comment by AlexanderRichey** [comment]
I'm not totally sure of what you're trying to achieve, but I think it might be possible to get the desired effect by placing the `<ModalProvider />` in the right place in your app. All that the `<ModalProvider />` does is set the node where the `<Modal />` is rendered, as [you can see in the source](https://github.com/AlexanderRichey/styled-react-modal/blob/master/src/ModalProvider.jsx). Otherwise, it might be best to implement your own modal for this specific use case.
