### ISSUE TITLE
Modal continuously calls `afterOpen` and `beforeClose` until the modal has been fully closed

### ISSUE THREAD

**Issue by ryanrouleau** [AlexanderRichey/styled-react-modal#41]
See an example here: https://codesandbox.io/s/styled-react-modal-better-fading-forked-8cip4?file=/src/index.js which is the official code sandbox demo just with `console.log` in `afterOpen` and `beforeClose`.

![Screen Shot 2021-04-22 at 4 20 56 PM](https://user-images.githubusercontent.com/15020000/115792004-baceeb00-a386-11eb-9fac-7f191ca57f1b.png)

This causes choppy, buggy behavior when closing the modal

**Comment by sjaakbanaan** [comment]
hi @ryanrouleau did you manage to find a fix for this by any chance?

**Comment by AlexanderRichey** [comment]
This is fixed in v3.0.0-alpha. I'm planning on releasing sometime this week. To test it out beforehand, run `yarn add styled-react-modal@alpha` or similar for npm. This is a major release since it adds support for es modules in addition to commonjs. If this causes problems for you, I'd consider doing a minor release with just the changes to fix this bug (it would be v2.2.0) in addition to the new major release.

**Comment by AlexanderRichey** [comment]
The fix has been released: https://github.com/AlexanderRichey/styled-react-modal/releases/tag/v3.0.0
