### ISSUE TITLE
Commonjs build breaks rollup (vitejs)

### ISSUE THREAD

**Issue by gdaybrice** [AlexanderRichey/styled-react-modal#50]
Hello, any chance we could export `styled-react-modal` as an esm module instead of commonjs (or both), this is causing issues when compiling with rollup (vitejs).

- My reproduction repo using vitejs + styled-react-modal https://github.com/vitejs/vite/issues/4935
- The thread about esbuilt and commonjs packages https://github.com/vitejs/vite/issues/4209#issuecomment-920938852

Thanks!

**Comment by uglow** [comment]
+1 - Tried a multitude of different CJS plugins and configurations for Vite, but still have the same problem as @blechatellier.

**Comment by AlexanderRichey** [comment]
Sorry for taking a while to get back to you. I hope to have some time to look into this over the next couple weekends or so—busy times at my day job at the moment. I'd be happy to review a PR in the meantime if anyone has the time, but otherwise I'm hoping to address all the open issues before the new year.

**Comment by fabianonunes** [comment]
It may not be necessary to export the library in another format. I think passing [libraryExport](https://v4.webpack.js.org/configuration/output/#outputlibraryexport)="default" to webpack config is enough:

```diff
// webpack.config.js
output: {
  path: path.resolve(__dirname, "build"),
  filename: "index.js",
  libraryTarget: "commonjs2",
  library: "styled-react-modal"
+ libraryExport: "default"
},
```

This isn't a Vite issue but a [@rollup/plugin-commonjs](https://github.com/rollup/plugins/tree/master/packages/commonjs) bug introduced by the refactoring done in rollup/plugins#537.

You can also downgrade `@rollup/plugin-commonjs` to version 15.0.0.

**Comment by AlexanderRichey** [comment]
Hi @uglow and @blechatellier, I just published v3.0.0-alpha which uses rollup and exposes an mjs build. If you have a minute during this week, it would be great if you could test it out. You'll just need to run `yarn add styled-react-modal@alpha` or similar for npm. Everything seems to be working on a little vite project I started locally, but since I'm not really familiar with vite it would be great to have someone like you make sure I didn't miss anything.

**Comment by gdaybrice** [comment]
@AlexanderRichey thanks so much, will give it a try and report back.

**Comment by gdaybrice** [comment]
@AlexanderRichey works as expected now, thanks for your help!

**Comment by AlexanderRichey** [comment]
The fix has been released: https://github.com/AlexanderRichey/styled-react-modal/releases/tag/v3.0.0
