### ISSUE TITLE
Animate backgroundComponent?

### ISSUE THREAD

**Issue by davidcsally** [AlexanderRichey/styled-react-modal#6]
Great library! 

I was wondering if it was possible to animate the `backgroundComponent` provided to `<ModalProvider />`? In the example, it looks like only the content of the modal is animated - not the overlay.

Thanks!

**Comment by AlexanderRichey** [comment]
Hi @davidcsally - sorry for taking so long to get back to you. One strategy to do this is to bring the background into the modal itself so that you can control its animation using the `afterOpen()` and `beforeClose()` hooks. Here is a sandbox where I sketched this approach: https://codesandbox.io/s/vqjxzn96v0

I'd like to develop a nice API that would allow you to control the `<BackgroundComponent />` from the `<Modal />`, but I haven't come up with a way of making it straightforward yet. One idea I had was to pass a background props object to the lifecycle methods, which the consumer could adjust and return, and then pass those props through to the background component in the render method. This would probably get the job done, but I'd like to explore some other possibilities before I add this functionality.
